name: Modi_CI

on:
  push:
    branches: [ master ]

jobs:
  deploy-ios-beta:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      # Install project deps & set env vars
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
           ${{ runner.os }}-yarn-
      
      - name: Install node_modules
        run: yarn install --prefer-offline

      - name: Install ios/Pods
        run: cd ios && pod install

      - name: Set env
        run: |
          echo {\"API_URL\":\"${{ secrets.API_URL }}\"} > src/env.json

      # Allows fastlane match to pull provisioning profiles from other git repo
      - uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to TestFlight
        env:
          MATCH_REPO: ${{ secrets.MATCH_REPO }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASS }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APP_ID: ${{ secrets.APP_ID }}
          SIGNING_ID: ${{ secrets.SIGNING_ID }}
          DEV_TEAM_ID: ${{ secrets.DEV_TEAM_ID }}
          ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
        run: |
          export FASTLANE_PASSWORD=${{ secrets.FASTLANE_PASSWORD }}
          cd ios && fastlane beta --verbose

