name: Modi_CI

on:
  push:
    branches: [ master ]

jobs:
  deploy-ios-beta:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      # Allows fastlane match to pull provisioning profiles from other git repo
      - uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Allows GH actions to cache node_modules
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: |
          yarn install
          cd ios && pod install

      - name: Set env
        run: |
          echo {\"API_URL\":\"${{ secrets.API_URL }}\"} > src/env.json

      - name: Deploy to TestFlight
        env:
          MATCH_REPO: ${{ secrets.MATCH_REPO }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASS }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APP_ID: ${{ secrets.APP_ID }}
          SIGNING_ID: ${{ secrets.SIGNING_ID }}
          DEV_TEAM_ID: ${{ secrets.DEV_TEAM_ID }}
          ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        run: |
          cd ios && fastlane beta --verbose

