name: Modi_CI

on:
  push:
    branches: [ master ]

jobs:
  deploy-ios-beta:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache_node_modules
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      
      - name: Install node_modules
        if: steps.cache_node_modules.outputs.cache_hit != 'true'
        run: yarn install

      - uses: actions/cache@v2
        id: cache_pods
        path: ios/Pods
        key: ${{ runner.os }}-%{{ hashFiles('ios/Podfile.lock') }}

      - name: Install pods
        if: steps.cache_pods.outputs.cache_hit != 'true'
        run: cd ios && pod install

      - name: Set env
        run: yarn env:prod

      # Allows fastlane match to pull provisioning profiles from other git repo
      - uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to TestFlight
        env:
          MATCH_REPO: ${{ secrets.MATCH_REPO }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASS }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APP_ID: ${{ secrets.APP_ID }}
          SIGNING_ID: ${{ secrets.SIGNING_ID }}
          DEV_TEAM_ID: ${{ secrets.DEV_TEAM_ID }}
          ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
        run: |
          export FASTLANE_PASSWORD=${{ secrets.FASTLANE_PASSWORD }}
          export FASTLANE_USER=${{ secrets.FASTLANE_USER }}
          cd ios && fastlane beta --verbose

